# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'nokogiri'
gem 'geocoder'
gem 'gender_detector'
gem 'activesupport'
gem 'descriptive_statistics'
gem 'byebug'
